# .github/workflows/sync.yaml
name: S3 sync action

on:
  workflow_dispatch:
  push:
    branches:
      - main

# <-- CORRECCIÓN: 'permissions' debe estar al nivel raíz, no dentro de 'on'.
permissions:
  id-token: write
  contents: read

# <-- CORRECCIÓN: 'jobs' debe2 estar al nivel raíz, no dentro de 'on'.
jobs:
  sync:
    # <-- CORRECCIÓN: 'ubuntu-latest' en lugar de 'ubuntu-lastest'.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # <-- MEJORA: Usar una versión más reciente de la acción.
        uses: actions/checkout@v4

      - name: Connect to AWS
        # <-- MEJORA: Usar una versión más reciente de la acción.
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: awssyncsession
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          # <-- CORRECCIÓN: El parámetro es 'aws-region' y no se necesita el '$'.
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync bucket
        # El comando 'sync' está bien escrito.
        run: aws s3 sync ./files/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
